name: secrete demo
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    check-secrets:
        runs-on: ubuntu-latest
        
        steps:
            - name: to check the secrete is present or not
              env:
                SECRET_VAL: ${{ secrets.MY_SECRET }}
              run: |
                if [ -n "$SECRET_VAL"]; then
                 echo "the secret is present: true"
                else
                 echo "the secret is not present: false"
                fi
            - name: attempt to print the sercret directly
              run: |
                echo "the secret value is: ${{ secrets.MY_SECRET }}"